### ISSUE TITLE
duda alineación vertical elementos dentro de un div

### ISSUE THREAD

**Issue by victoriapenasmiro** [victoriapenasmiro/exercicis_diw_202021#1]
https://github.com/victoriapenasmiro/exercicis_diw_202021/blob/5d9cdd3fff331c70f2a7570ef24222f236b1cb8d/e01.1_CSS%20Basic/css/styles.css#L13

Hola @classicoman2

Como puedes comprobar en el CSS he alineado el h1 y el h2 verticalmente dentro de su contenedor forzando un padding, ¿Cuál sería la mejor forma de hacerlo que que se centre automáticamente?

He estado investigando y he encontrado que puedo hacerlo mediante las propiedades:

  display: flex;
  align-items: center;

Sin embargo, me quedaba todo desconfigurado.

A pesar de esto, la práctica está finalizada, he tardado algo más de dos horas, supongo que por la falta de práctica ... ¿Cómo ves el código?

Gracias!

**Comment by victoriapenasmiro** [comment]
@classicoman2, crec que no varem comentar aquest dubte a classe. ¿li has pegat una ullada?

**Comment by classicoman2** [comment]
La solució adoptada en aquest cas me pareix correcta: pots emprar margin-left o margin-right per col·locar l'element.

La solució a l'exercici és correcta.
