### ISSUE TITLE
no he emplenat codi

### ISSUE THREAD

**Issue by victoriapenasmiro** [victoriapenasmiro/exercicis_diw_202021#3]
https://github.com/victoriapenasmiro/exercicis_diw_202021/blob/30b2479074e25c3a455fe47520b9bb5cb5261cb0/e02.1_Flexbox/flexbox-cards.css#L39

Hola @classicoman2,
Tenc un parell de dubtes damunt aquest exercisi, En relació amb aquesta linea, veig que esperes que posem codi aqui, però jo ho he aconseguit sense omplir aquesta part, i al seu lloc he posat es CSS a .card .text (lineas del 30 al 31). Crec que no és lo que esperaves?

Gracis

**Comment by classicoman2** [comment]
No, no és imprescindible escriure codi allà, crec que ho vaig posar per si de cas. El més important en tot cas és la resta de l'exercici.

**Comment by victoriapenasmiro** [comment]
ok
