### ISSUE TITLE
display:flex als elements filss

### ISSUE THREAD

**Issue by victoriapenasmiro** [victoriapenasmiro/exercicis_diw_202021#4]
https://github.com/victoriapenasmiro/exercicis_diw_202021/blob/30b2479074e25c3a455fe47520b9bb5cb5261cb0/e02.1_Flexbox/flexbox-cards.css#L14

Hola @classicoman2,
Per aconseguir el diseny tal i comproposaves he tengut que indicar als contenidors fills de .cards display:flex un altre pic. ¿És correcte? Pensava que s'heredava del div pare.

Gràcies

**Comment by classicoman2** [comment]
No, la propietat `display` no s'hereda, així que els fills tenen el valor per defecte, _block_
